name: Unzip File

on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install unzip
      run: sudo apt-get install -y unzip

    - name: Unzip file
      run: unzip v18/v18 brawl.zip -d path/to/destination
